version: '3'
services:
  servico-conta:
    build: 
      context: ./servico-conta
    ports:
      - "3000:3000"
    environment:
      - FLASK-APP=/root/servico-conta
      - FLASK_RUN_PORT=3000
    command: python3 app.py
  servico-pedido:
    build:
      context: ./servico-pedido
    ports:
      - 3001:3000
    command: python3 app.py 